// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewProject.Infrastructure.Persistence;

#nullable disable

namespace NewProject.Infrastructure.Migrations
{
    [DbContext(typeof(MultipleFormatDbContext))]
    [Migration("20260922131912_CreateMultiFormatTables")]
    partial class CreateMultiFormatTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.DepartmentShiftChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentShift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormRequestId")
                        .HasColumnType("int");

                    b.Property<string>("NewDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewShift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormRequestId");

                    b.ToTable("MFR_DEPARTMENT_SHIFT_CHANGE_REQUEST");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.FormRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MFR_FORM_REQUEST");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.PermissionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormRequestId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormRequestId");

                    b.ToTable("MFR_PERMISSION_REQUEST");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.TimeAdjustmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("EntryTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ExitTime")
                        .HasColumnType("time");

                    b.Property<int>("FormRequestId")
                        .HasColumnType("int");

                    b.Property<string>("MissingPunchType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormRequestId");

                    b.ToTable("MFR_TIME_ADJUSTMENT_REQUEST");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VacationDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormRequestId");

                    b.ToTable("MFR_VACATION_REQUEST");
                });

            modelBuilder.Entity("NewProject.Domain.Entities.IDM.IDMAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("DomainUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DOMAIN_USER_NAME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.HasKey("Id");

                    b.HasIndex("DomainUserName")
                        .IsUnique();

                    b.ToTable("IDM_ACCOUNT");
                });

            modelBuilder.Entity("NewProject.Domain.Entities.IDM.IDMAccountRole", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("IDM_ACCOUNT_ROLE");
                });

            modelBuilder.Entity("NewProject.Domain.Entities.IDM.IDMRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("IDM_ROLE");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.DepartmentShiftChangeRequest", b =>
                {
                    b.HasOne("MultipleFormat.Domain.Entities.FlowRequests.FormRequest", "FormRequest")
                        .WithMany()
                        .HasForeignKey("FormRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormRequest");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.PermissionRequest", b =>
                {
                    b.HasOne("MultipleFormat.Domain.Entities.FlowRequests.FormRequest", "FormRequest")
                        .WithMany()
                        .HasForeignKey("FormRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormRequest");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.TimeAdjustmentRequest", b =>
                {
                    b.HasOne("MultipleFormat.Domain.Entities.FlowRequests.FormRequest", "FormRequest")
                        .WithMany()
                        .HasForeignKey("FormRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormRequest");
                });

            modelBuilder.Entity("MultipleFormat.Domain.Entities.FlowRequests.VacationRequest", b =>
                {
                    b.HasOne("MultipleFormat.Domain.Entities.FlowRequests.FormRequest", "FormRequest")
                        .WithMany()
                        .HasForeignKey("FormRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormRequest");
                });

            modelBuilder.Entity("NewProject.Domain.Entities.IDM.IDMAccountRole", b =>
                {
                    b.HasOne("NewProject.Domain.Entities.IDM.IDMAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewProject.Domain.Entities.IDM.IDMRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
